Makes the execute post actions compatible for the dcg
contao-community-alliance/contao-multicolumnwizard-bundle pull request #92
Opened 2020-11-08 16:34 UTC by baumannsven

This is the fix for can use e.g. file tree widget with the dcg.

2020-11-09 12:15 UTC, zonky2 approved these changes
works fine

2020-11-09 12:17 UTC, discordier approved these changes
LGTM

2020-11-09 12:21 UTC, baumannsven commented
Travis build is failing. After the test build works fine, i switch the label wip => rtm.

2020-11-09 18:05 UTC, baumannsven commented
@discordier I have add the two dcg packages to require-dev section. So after adds the package, the travis build crashes. I have no idea, what I can do. Can you please take a look at this?

2020-11-09 18:54 UTC, discordier requested changes
Please recheck `.travis.yml`.

2020-11-09 18:54 UTC, discordier commented on .travis.yml
> +sudo: false
Not needed anymore. See https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments

2020-11-09 18:54 UTC, discordier commented on .travis.yml
> -      export COMPOSER_ROOT_VERSION=${TRAVIS_TAG}
Please revert this, exporting and echoing below helps pin point problems as this PR is currently having.
We now have no clue at all what composer thinks it has installed as root package and therefore do not know how to make it install dcg.

2020-11-09 18:54 UTC, discordier commented on composer.json
> +    "contao/core-bundle": "~4.4.0",
Why the downgrade to `4.4.0`? AFAIR we upgraded to at least `4.4.8` for a reason (some bug that was incompatible with this extension).

2020-11-09 18:59 UTC, zonky2 commented on composer.json
> +    "contao/core-bundle": "~4.4.0",
https://github.com/menatwork/contao-multicolumnwizard-bundle/commit/34adec0046a3db598b9b00b6044f6d4167df9ffa#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

2020-11-10 05:59 UTC, baumannsven commented on .travis.yml
> +sudo: false
Done

2020-11-10 05:59 UTC, baumannsven commented on .travis.yml
> -      export COMPOSER_ROOT_VERSION=${TRAVIS_TAG}
Done

2020-11-10 05:59 UTC, baumannsven commented on composer.json
> +    "contao/core-bundle": "~4.4.0",
Done

2020-11-10 06:43 UTC, baumannsven commented on .travis.yml
> +sudo: false
Not working. I not remove this line.

https://travis-ci.org/github/menatwork/contao-multicolumnwizard-bundle/jobs/742631080

2020-11-10 11:50 UTC, baumannsven commented
@stefanheimes  I temporarily removed the two necessary development packages from DC General, so we called by phone.

These will be added again later.

2020-11-10 12:17 UTC, discordier commented on .travis.yml
> +sudo: false
What do you mean by not working? Sudo is not needed anymore... I removed it from many `.travis.yml` files already.

2020-11-10 14:36 UTC, baumannsven commented on .travis.yml
> +sudo: false
Oh sorry. I think do you mean the before script setting

2020-11-10 21:44 UTC, merged